#!/bin/sh

python -u run.py \
    --is_training 1 \
    --training_stage 2 \
    --device cuda \
    --dataset_name mnist \
    --train_data_paths /data/moving-mnist-example/moving-mnist-train.npz \
    --valid_data_paths /data/moving-mnist-example/moving-mnist-valid.npz \
    --save_dir checkpoints/mnist_seemore_stage_2 \
    --model_name seemore \
    --reverse_input 1 \
    --img_width 64 \
    --img_channel 1 \
    --input_length 10 \
    --total_length 20 \
    --num_hidden 128,128,128,128 \
    --filter_size 5 \
    --stride 1 \
    --patch_size 4 \
    --layer_norm 0 \
    --decouple_beta 0.1 \
    --reverse_scheduled_sampling 1 \
    --r_sampling_step_1 5000 \
    --r_sampling_step_2 10000 \
    --r_exp_alpha 2500 \
    --lr_alpha 0.0001 \
    --lr_beta 0.0000001 \
    --batch_size 8 \
    --max_iterations 10000 \
    --display_interval 50 \
    --test_interval 200 \
    --pretrained_model path_to_seemore_stage_1.ckpt \
